# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-15 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('expense', models.PositiveSmallIntegerField(default=0)),
                ('income', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
